#!/usr/bin/env python3
"""
Auto-generate FINDINGS.md from pattern analysis outputs.
Reads all .md files in patterns/ and combines them into a single report.
"""

import re
from datetime import datetime
from pathlib import Path

PATTERNS_DIR = Path(__file__).parent / "patterns"
OUTPUT_FILE = Path(__file__).parent / "FINDINGS.md"

PATTERN_ORDER = [
    ("session_outcomes", "Session Outcomes"),
    ("error_taxonomy", "Error Taxonomy"),
    ("retry_loops", "Retry Loops & Wasted Effort"),
    ("self_scoring", "Self-Scoring Patterns"),
    ("tool_misuse", "Tool Misuse"),
    ("hook_rejections", "Hook Rejections"),
    ("large_file_errors", "Large File Errors"),
    ("project_stats", "Project & Usage Stats"),
    ("prompting_style", "Prompting Style"),
]


def extract_summary(content, max_lines=80):
    """Extract the summary/top section of a pattern output, skip per-session details."""
    lines = content.split("\n")
    summary_lines = []
    in_detail = False

    for line in lines:
        upper = line.strip().upper()
        if any(skip in upper for skip in [
            "PER-SESSION DETAILS", "DETAILED FINDINGS", "PER SESSION",
            "ALL INSTANCES", "FULL LISTING", "RAW DATA",
        ]):
            in_detail = True
        if in_detail:
            continue
        summary_lines.append(line)
        if len(summary_lines) >= max_lines:
            summary_lines.append("... [truncated, see full output in patterns/]")
            break

    return "\n".join(summary_lines).rstrip()


def main():
    sections = []

    for name, title in PATTERN_ORDER:
        md_path = PATTERNS_DIR / f"{name}.md"
        if not md_path.exists():
            sections.append(f"## {title}\n\n*Not yet generated. Run `python3 patterns/{name}.py`*\n")
            continue

        content = md_path.read_text()
        summary = extract_summary(content)
        sections.append(f"## {title}\n\n```\n{summary}\n```\n")

    report = f"""# Transcript Analysis Findings

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This file is auto-generated by `generate_findings.py` from pattern analysis outputs in `patterns/`.
For full details, see individual files in `patterns/`.

---

{"---\n\n".join(sections)}"""

    OUTPUT_FILE.write_text(report)
    print(f"Generated {OUTPUT_FILE} ({len(sections)} sections)")


if __name__ == "__main__":
    main()
