#!/usr/bin/env python3
"""
Auto-generate FINDINGS.md from pattern analysis outputs.
Reads all .md files in patterns/ and combines them into a single report.
"""

import re
from datetime import datetime
from pathlib import Path

PATTERNS_DIR = Path(__file__).parent / "patterns"
OUTPUT_FILE = Path(__file__).parent / "FINDINGS.md"

PATTERN_ORDER = [
    ("session_outcomes", "Session Outcomes"),
    ("error_taxonomy", "Error Taxonomy"),
    ("retry_loops", "Retry Loops & Wasted Effort"),
    ("self_scoring", "Self-Scoring Patterns"),
    ("tool_misuse", "Tool Misuse"),
    ("hook_rejections", "Hook Rejections"),
    ("large_file_errors", "Large File Errors"),
    ("project_stats", "Project & Usage Stats"),
    ("prompting_style", "Prompting Style"),
]


def extract_summary(content):
    """Return the full pattern content for inclusion in FINDINGS.md."""
    return content.rstrip()


def main():
    sections = []

    for name, title in PATTERN_ORDER:
        md_path = PATTERNS_DIR / f"{name}.md"
        if not md_path.exists():
            sections.append(f"## {title}\n\n*Not yet generated. Run `python3 patterns/{name}.py`*\n")
            continue

        content = md_path.read_text()
        summary = extract_summary(content)
        sections.append(f"## {title}\n\n{summary}\n")

    report = f"""# Transcript Analysis Findings

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This file is auto-generated by `generate_findings.py` from pattern analysis outputs in `patterns/`.
For full details, see individual files in `patterns/`.

---

{"---\n\n".join(sections)}"""

    OUTPUT_FILE.write_text(report)
    print(f"Generated {OUTPUT_FILE} ({len(sections)} sections)")


if __name__ == "__main__":
    main()
